### ISSUE TITLE
Not using custom dump summary

### ISSUE THREAD

**Issue by inspire22** [MrJoy/rspec-gc-control#1]
I'm using ruby 2.0 and rails 3.  It seems to be working (I put some lines in the gem to print the gc execution time), but there's no result printed in the output log

Is there a reason baseformatter wouldn't be called properly?

**Comment by MrJoy** [comment]
What's your `.rspec` and rspec commandine look like?  Might depend on the formatter or formatting options you've chosen?

**Comment by inspire22** [comment]
My .rspec is just "--color", so not sure what it could be related to that.  I removed it but it still wasn't running.

Rspec command is "rspec spec/controllers/topic_controller_spec.rb"

**Comment by inspire22** [comment]
I had rspec locked at 2.11 because of some bug awhile back.  Updating this to the latest 2.14 fixed this issue, thanks for a great project :)
