### ISSUE TITLE
undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by slava-nikulin** [MrJoy/rspec-gc-control#4]
Can you help me to solve this issue?

Failure/Error: if(@gc_every_n_examples > 0)
Trace:
/.rvm/gems/ruby-1.9.3-p551@rails3112/bundler/gems/rspec-gc-control-bc67f4b6fbb6/lib/rspec-gc-control/configuration.rb:24:in `gc_if_needed'
/.rvm/gems/ruby-1.9.3-p551@rails3112/bundler/gems/rspec-gc-control-bc67f4b6fbb6/lib/rspec-gc-control/example.rb:16:in`run_after_example'

**Comment by MrJoy** [comment]
My apologies for not seeing this until now.  I'll take a peek this afternoon!

**Comment by MrJoy** [comment]
... it would be helpful though, if you could tell me what exact version of Rspec you're using.  Actually, if you're comfortable sharing it, your `Gemfile.lock` would be useful to make it easier to reproduce this.

**Comment by MrJoy** [comment]
Actually, it looks like you haven't configured the relevant setting?  Try explicitly setting it to, say, 10?

**Comment by MrJoy** [comment]
``` ruby
RSpec.configure do |c|
  c.gc_every_n_examples = 10
end
```

**Comment by slava-nikulin** [comment]
@MrJoy, thank you for response, your're right!

**Comment by MrJoy** [comment]
Awesome!
